services:
  db:
    container_name: db-container
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - db-connect
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    container_name: backend-container
    platform: linux/amd64
    build: #이미지 build 블록 관련 설정
      context: ./backend
      cache_to:
        - type=local,dest=/tmp/.buildx-cache/backend,mode=max
        #local은 file을 의미함
        #type: types of cache
        #src: cache를 저장할 경로
        #mode: cache의 저장 방식(max: 최대한 많은 cache data를 저장
      # path from calling cache
      cache_from:
        - type=local,src=/tmp/.buildx-cache/backend

    image: wonnho/backend:latest
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    networks:
      - db-connect
      - backend-connect
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend-container
    platform: linux/amd64
    build:
      context: ./frontend
      cache_to:
        - type=local,dest=/tmp/.buildx-cache/frontend,mode=max

      cache_from:
        - type=local,src=/tmp/.buildx-cache/frontend

      args:
        VITE_API_URL: ${VITE_API_URL}
    image: wonnho/frontend:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend-connect
    volumes:
      - /etc/letsencrypt/live/54.180.238.27.sslip.io/fullchain.pem:/etc/letsencrypt/live/54.180.238.27.sslip.io/fullchain.pem
      - /etc/letsencrypt/live/54.180.238.27.sslip.io/privkey.pem:/etc/letsencrypt/live/54.180.238.27.sslip.io/privkey.pem
    depends_on:
      - backend
      - db

volumes:
  db-volume:

networks:
  db-connect:
  backend-connect:
