name: ssh
on:
  push:
    branches:
      - main

jobs:
  ssh-agent:
    runs-on: ubuntu-24.04

    steps:
      - name: 테스트 ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
